### ISSUE TITLE
[Off-Topic] ERROR LISTE BY FREETZ-NG

### ISSUE THREAD

**Issue by dreirund** [MasterRoCcO/i-matik#1]
Dear "@MasterRoCcO",

I write you this way because you have been blocked [1] in the thread "gcc 3.4: gcc14 compatibility, thx @dreirund" [2] and thus are not anymore able to answer the question

> *Why should @fda77 test it when I actually did test it on the real hardware?*
> 
> *@fda77 has the knowledge on how to make Freetz-NG modifications. I have the hardware. And I tested it.*
> 
> *(Why) isn't that enough?*

which I raised there [3] and am still curious to get an answer.

So:  
Why does @fda77 needs to test it personally?

Regards!

[1]
https://github.com/Freetz-NG/freetz-ng/commit/e38907588802bc565d1f9c504e12a02b2542919e#commitcomment-146506277

[2]
https://github.com/Freetz-NG/freetz-ng/commit/e38907588802bc565d1f9c504e12a02b2542919e

[3]
https://github.com/Freetz-NG/freetz-ng/commit/e38907588802bc565d1f9c504e12a02b2542919e#commitcomment-146504254

**Comment by MasterRoCcO** [comment]
FDA knows why!

He should rather take care of these mistakes. 
Swapping the partition on FIT devices. View the other partition on FIT devices. You don't even need a FIT device for these errors.
https://www.ip-phone-forum.de/threads/das-updaten-flashen-per-freetz-ng-gui-neuer-fehler-fit-ger%C3%A4te-mit-fw-7-5x-erledigt.319058/

The source files for the 7530AX (source-files-FRITZ.Box_7530_AX-brcma9-07.56.tar.gz and source-files-FRITZ.Box_7530_AX-brcma9-07.80.tar.gz) are not corrupt as he claims, there are just a few targets missing in his patch files.
[7530AX.webm](https://github.com/user-attachments/assets/a8238189-4ceb-43a7-9126-32b56aa18858)

https://www.ip-phone-forum.de/threads/die-source-files-f%C3%BCr-die-7530ax-07-81-sind-auch-in-ordnung.319158/
I've had patches for this for a long time. But I don't see it anymore to give FDA something. Because you are portrayed as a nutcase, a liar and whatnot. And as he once said himself, we are all just traced monkeys!

Even if he should now supposedly no longer have 7490 in operation. Certainly no one will have bought the device from him. So he could sit down and take a look at the AVM portfw. No, he comes up with strange emergency solutions that don't even work properly.

Regarding ccid and pcsc-lite
https://www.ip-phone-forum.de/threads/ist-das-nun-der-neue-weg-den-fda-gehen-will.319190/



310-no_diffconfig.patch der 6670 fehler hat er ja nun gefixt 
https://www.ip-phone-forum.de/threads/fehler-in-diesem-patch-310-no_diffconfig-patch-der-6670.319121/

Der Bootmanager ist angeblich inkompatibl
https://www.ip-phone-forum.de/threads/der-bootmanager-ist-angeblich-inkompatibl.318623/

Aktuell bootet kein 7490 und 7590AX Image mehr (selbst getestet) Ergänzung patchelf probleme
https://www.ip-phone-forum.de/threads/aktuell-bootet-kein-7490-und-7590ax-image-mehr-selbst-getestet-erg%C3%A4nzung-patchelf-probleme.314675/
And that 2 times. 
And he only fixed them when I reported them.

**Comment by MasterRoCcO** [comment]
@dreirund 
Next mistake: The patches of @FDA77 are simply flawed.
https://github.com/Freetz-NG/freetz-ng/commit/c907031b980731a93dcc42bd39fe6a23bdc85d4a
7590AX Watch from approx. 18 min.
[Video](https://www.mediafire.com/file/6pm0ug7xm4n58gd/7590AX_mit_patch_fix.mkv/file)
7530AX Watch from approx. 15:40 min.
[Video](https://www.mediafire.com/file/6pm0ug7xm4n58gd/7590AX_mit_patch_fix.mkv/file) 

7581 and 7583 no longer work either.

**Comment by dreirund** [comment]
Hm, thanks for this.

Having skimmed over conversations between you, @fda77 and @MasterRoCcO, it seems to me that you could need some sort of "Konfliktbegleitung". (Mediation, [Restorative Circle](http://www.kreisgespraeche.org/einleitung/), &hellip;)

I think it would be really worth for the project if both of you would find a way to work together again, or at least not against each other.

Regards!

**Comment by MasterRoCcO** [comment]
How many more times should you try? They are blocked, amounts are deleted. I've been trying for 2 years, for me it's done. When I see mistakes, I like to say them again and again. He has to repair them himself. If he wants to, then he should take the first step.

**Comment by MasterRoCcO** [comment]
Next Error
https://github.com/Freetz-NG/freetz-ng/commit/73d5b848252dab0a230ca4a077ff5456e4533ccb
Now no images can be created for it at all.
https://github.com/Freetz-NG/freetz-ng/discussions/1056

**Comment by MasterRoCcO** [comment]
Next patch bug by activating kernel stuff
https://github.com/Freetz-NG/freetz-ng/commit/7cd6901264755d6b76bb045ee718d24585f9e317
Patch no work

**Comment by MasterRoCcO** [comment]
Doesn't work with kernel files!

4040 
https://github.com/Freetz-NG/freetz-ng/commit/806c27ee7e45ec635f19c610d0bd1435a5a86f15

5530
https://github.com/Freetz-NG/freetz-ng/commit/f672c7b4c7953f649c429c55cb24ca6ac52e5238

5590
https://github.com/Freetz-NG/freetz-ng/commit/20d6d56976a6f2837d3a8a88eb8ece1e05f19413

7530 thus also 7520 and 7520B
https://github.com/Freetz-NG/freetz-ng/commit/b286cbbea33783a26c5092bfb3c6e31e02e20634

7590AX
https://github.com/Freetz-NG/freetz-ng/commit/c907031b980731a93dcc42bd39fe6a23bdc85d4a
and
https://github.com/Freetz-NG/freetz-ng/commit/7cd6901264755d6b76bb045ee718d24585f9e317
